/** Pure presentation policy for progressive handwriting assistance. */
export const HANDWRITING_HINT_VERSION="1.0.0";
export const HANDWRITING_HINT_LEVELS=Object.freeze({TRACE:0,GHOST:1,STROKE_GUIDE:2,MINIMAL:3,RECALL:4});
const LEVEL_NAMES=Object.freeze(["trace","ghost","stroke-guide","minimal","recall"]);
const normalizeSignalNumber=value=>{const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):0};
export function normalizeHintLevel(value){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(4,Math.round(n))):0;}
export function initialHintLevel(signal={}){const state=String(signal?.state||"").toLowerCase(),confidence=normalizeSignalNumber(signal?.confidence),mastery=Number(signal?.mastery),effectiveMastery=Number.isFinite(mastery)?normalizeSignalNumber(mastery):null;if(state==="mastered"||(state==="stable"&&confidence>=.75)||(effectiveMastery!==null&&effectiveMastery>=.9&&confidence>=.6))return 3;if(state==="stable")return 2;if(state==="weak"||state==="recovering")return 1;return 0;}
export function adaptHintLevel(level,grade={}){const current=normalizeHintLevel(level),score=Number(grade?.overallSimilarity),reliable=grade?.scoreReliability==="high"||grade?.scoreReliability==="medium";if(!Number.isFinite(score)||!reliable)return current;if(score>=88)return Math.min(4,current+1);if(score<70)return Math.max(0,current-1);return current;}
export function shouldPresentStrokeFeedback(grade={}){const reliability=grade?.scoreReliability,score=Number(grade?.similarity),code=String(grade?.feedbackCode||"");if(reliability!=="high"&&reliability!=="medium")return false;if(Boolean(grade?.actionable))return true;return code!=="good"&&Number.isFinite(score)&&score<.92;}
export function requestMoreHelp(level){return Math.max(0,normalizeHintLevel(level)-1);}
export function hintLevelName(level){return LEVEL_NAMES[normalizeHintLevel(level)];}
export function hintProfile(level,{currentStrokeIndex=-1,referenceLength=0}={}){const normalized=normalizeHintLevel(level),current=Number.isInteger(currentStrokeIndex)&&currentStrokeIndex>=0&&currentStrokeIndex<referenceLength?currentStrokeIndex:-1;if(normalized===0)return Object.freeze({level:0,name:"trace",referenceMode:"all",opacity:.42,currentStroke:current,showStart:false,showDirection:false,showNumber:false});if(normalized===1)return Object.freeze({level:1,name:"ghost",referenceMode:"all",opacity:.16,currentStroke:current,showStart:false,showDirection:false,showNumber:false});if(normalized===2)return Object.freeze({level:2,name:"stroke-guide",referenceMode:"current",opacity:.36,currentStroke:current,showStart:current>=0,showDirection:current>=0,showNumber:false});if(normalized===3)return Object.freeze({level:3,name:"minimal",referenceMode:"none",opacity:0,currentStroke:current,showStart:current>=0,showDirection:false,showNumber:current>=0});return Object.freeze({level:4,name:"recall",referenceMode:"none",opacity:0,currentStroke:-1,showStart:false,showDirection:false,showNumber:false});}
