const IS_LEGACY = new URLSearchParams(location.search).get('legacy') === '1';

let createEmptyCard, fsrs, Rating;
const FSRS_URL="./vendor/ts-fsrs-5.4.1.mjs";
const DATA_URL="./kanji-data.json";
const WORDS_URL=ch=>"https://kanjiapi.dev/v1/words/"+encodeURIComponent(ch);
const STORAGE="kanji5-v1";const CARDS_STORAGE="kanji5-v1-cards";const REVIEWS_STORAGE="kanji5-v1-reviews";
const DEFAULTS={dailyNew:5,retention:.90,maxInterval:36500,dailyGoal:20,leechThreshold:8};
const CUSTOM_STUDY_STORAGE='kanji5-v2-custom-study-filter';
let state=window.__KANJI5_STATE__.createInitial({settings:DEFAULTS});let scheduler;let customStudyCore=null;let customStudyFilter=null;
try{customStudyFilter=JSON.parse(sessionStorage.getItem(CUSTOM_STUDY_STORAGE)||'null')}catch(_){customStudyFilter=null}
const $=id=>document.getElementById(id);const {todayKey,deviceId,eventId,save,loadSaved,reviveCard,hydrateCards}=window.__KANJI5_STATE__;
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function speak(text){if(!text)return;if(!("speechSynthesis"in window)){toast("مرورگر شما از خواندن صدا پشتیبانی نمی‌کند.");return}try{const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(_){toast("پخش صدا ممکن نشد.")}}
function initScheduler(){scheduler=fsrs({request_retention:state.settings.retention,maximum_interval:state.settings.maxInterval,enable_fuzz:true,enable_short_term:true,learning_steps:["1m","10m"],relearning_steps:["10m"]})}
async function loadDeck(){if(IS_LEGACY&&$("loadStatus"))$("loadStatus").textContent="در حال دریافت فهرست Jōyō...";const prefetched=window.__KANJI5_P0_DATA_PROMISE;if(prefetched){const all=await prefetched;if(Array.isArray(all)&&all.length===2136){state.deck=canonicalizeDeckReadings(all);localStorage.setItem("kanji5-deck",JSON.stringify(state.deck));return}}const res=await fetch(DATA_URL,{cache:"force-cache"});if(!res.ok)throw new Error("Could not load local kanji dataset");const data=await res.json();const all=Array.isArray(data)?data:(data.kanji||[]);if(all.length!==2136)throw new Error(`Runtime kanji dataset must contain 2136 entries, got ${all.length}`);state.deck=canonicalizeDeckReadings(all);localStorage.setItem("kanji5-deck",JSON.stringify(state.deck))}
function canonicalizeDeckReadings(deck){const core=window.__KANJI5_EDU_CORE__;if(!core?.canonicalizeItemReadings||!Array.isArray(deck))return deck;return deck.map(item=>core.canonicalizeItemReadings(item))}
function loadDeckFromCache(){try{const x=JSON.parse(localStorage.getItem("kanji5-deck")||"null");if(Array.isArray(x)&&x.length===2136){state.deck=canonicalizeDeckReadings(x);return true}}catch(_){}return false}
function ensureCard(item){if(!state.cards[item.id])state.cards[item.id]={card:createEmptyCard(),reviews:0,lapses:0,learnedAt:null};return state.cards[item.id]}
function dueNow(card){return card&&card.due&&new Date(card.due)<=new Date()}
function educationQueuePriority(item,knowledge,now=Date.now()){const core=window.__KANJI5_EDU_CORE__;if(!core||!item)return 0;const entry=knowledge?.[item.character]||{};const signal=core.educationSchedulerSignal?core.educationSchedulerSignal(entry):null;if(!signal)return 0;const latest=[entry.meaning,entry.reading,entry.production,entry.vocabulary,entry.context].map(s=>s?.lastAt).filter(Boolean).sort().pop()||'';const ageDays=latest?Math.max(0,now-Date.parse(latest))/86400000:0;const recallEvidence=entry.attributeRecallEvidence||entry.componentEvidence;const attributeRecallValues=['meaning','reading'].map(mode=>Number(recallEvidence?.[mode]?.weakness)).filter(Number.isFinite);const attributeRecallWeakness=attributeRecallValues.length?Math.max(...attributeRecallValues):0;return signal.weakness*.7+(1-signal.weakestSkillMastery)*.3+Math.min(1,ageDays/14)*.15+attributeRecallWeakness*.25}
function jlptRank(item){const rank={N5:0,N4:1,N3:2,N2:3,N1:4};return rank[item?.jlpt]??5}
function newCardPriority(item,knowledge,now=Date.now()){const entry=knowledge?.[item.character]||{};const latest=[entry.meaning,entry.reading,entry.production,entry.vocabulary,entry.context].map(s=>s?.lastAt).filter(Boolean).sort().pop()||'';const ageDays=latest?Math.max(0,now-Date.parse(latest))/86400000:0;return educationQueuePriority(item,knowledge,now)+Math.min(1,ageDays/30)*.1}
function buildDefaultQueue(){
  let knowledge={};
  try{knowledge=JSON.parse(localStorage.getItem('kanji5-v1.2-knowledge')||'{}')}catch(_){}
  const now=Date.now();
  const dueItems=state.deck.filter(item=>state.cards[item.id]?.card&&dueNow(state.cards[item.id].card)).map(item=>({item,card:reviveCard(state.cards[item.id].card)}));
  dueItems.sort((a,b)=>{
    const aLate=Math.max(0,(now-new Date(a.card.due).getTime())/86400000),bLate=Math.max(0,(now-new Date(b.card.due).getTime())/86400000);
    const aScore=aLate*.6+educationQueuePriority(a.item,knowledge,now)*.4,bScore=bLate*.6+educationQueuePriority(b.item,knowledge,now)*.4;
    return bScore-aScore||new Date(a.card.due)-new Date(b.card.due)
  });
  const due=dueItems.map(x=>x.item.id);
  const remaining=Math.max(0,state.settings.dailyNew-state.todayNew);
  const newCards=state.deck.filter(item=>!state.cards[item.id]).sort((a,b)=>{
    const level=jlptRank(a)-jlptRank(b);if(level)return level;
    const priority=newCardPriority(b,knowledge,now)-newCardPriority(a,knowledge,now);if(Math.abs(priority)>.0001)return priority;
    const af=Number.isFinite(Number(a.frequency))?Number(a.frequency):Infinity,bf=Number.isFinite(Number(b.frequency))?Number(b.frequency):Infinity;
    return af-bf||String(a.character).localeCompare(String(b.character))
  }).slice(0,remaining).map(item=>item.id);
  state.queue=[...due,...newCards];
  return state.queue;
}
function buildQueue(){
  if(customStudyFilter&&customStudyCore?.selectCustomStudyItems){
    const selected=customStudyCore.selectCustomStudyItems({
      deck:state.deck,
      cards:state.cards||{},
      learner:window.__KANJI5_V19_LEARNER_MODEL__?.read?.()||{},
      filter:customStudyFilter,
      dailyNew:state.settings.dailyNew,
      todayNew:state.todayNew,
      now:Date.now()
    });
    state.queue=[...selected.ids];
    return state.queue;
  }
  return buildDefaultQueue();
}
async function setCustomStudyFilter(filter={}){
  if(!customStudyCore)customStudyCore=await import('./v2-custom-study-core.js');
  customStudyFilter=customStudyCore.normalizeCustomStudyFilter(filter);
  try{sessionStorage.setItem(CUSTOM_STUDY_STORAGE,JSON.stringify(customStudyFilter))}catch(_){ }
  buildQueue();
  state.current=null;
  state.revealed=false;
  next();
  return state.queue.length;
}
function clearCustomStudyFilter(){
  customStudyFilter=null;
  try{sessionStorage.removeItem(CUSTOM_STUDY_STORAGE)}catch(_){ }
  buildQueue();
  state.current=null;
  state.revealed=false;
  next();
  return true;
}
function formatInterval(card){const mins=Math.max(0,Math.round((new Date(card.due)-Date.now())/60000));if(mins<60)return`${Math.max(1,mins)}m`;const h=mins/60;if(h<24)return`${Math.round(h)}h`;return`${Math.round(h/24)}d`}
function formatMeta(k){const chips=[];if(state.cards[k.id]?.leech)chips.push({t:"🥴 Leech",cls:" leech"});if(k.frequency)chips.push({t:`頻度 #${k.frequency}`});if(k.grade)chips.push({t:`Jōyō grade ${k.grade}`});if(k.jlpt)chips.push({t:k.jlpt});chips.push({t:`${k.strokes} strokes`});return chips.map(x=>`<span class="chip${x.cls||""}">${x.t}</span>`).join("")}
function exampleComplexity(example,k){const word=String(example?.word||''),reading=String(example?.reading||'');const otherKanji=[...word].filter(ch=>/[\u3400-\u9fff]/.test(ch)&&ch!==k.character).length;return otherKanji*6+Math.max(0,[...word].length-2)*1.5+Math.max(0,[...reading].length-4)*.35}
async function fetchExamples(k){if(state.examples[k.id])return;try{const res=await fetch(WORDS_URL(k.character),{cache:'force-cache'});if(!res.ok)return;const data=await res.json(),seen=new Set(),candidates=[];for(const e of data){for(const v of(e.variants||[])){const term=String(v.written||''),reading=String(v.pronounced||'');const meaning=(e.meanings||[]).flatMap(m=>m?.glosses||[]).slice(0,2).join('; ');if(!term||!reading||!meaning||!term.includes(k.character)||seen.has(term+'|'+reading))continue;seen.add(term+'|'+reading);candidates.push({word:term,reading,meaning})}}candidates.sort((a,b)=>exampleComplexity(a,k)-exampleComplexity(b,k)||a.word.localeCompare(b.word));state.examples[k.id]=candidates.slice(0,4);save()}catch(_){}}
function reviewSnapshot(){const id=state.current;if(!id)return{active:false};const item=state.deck.find(x=>x.id===id);if(!item)return{active:false};const rec=state.cards[item.id];return{active:true,character:item.character,isNew:!rec,revealed:Boolean(state.revealed),meanings:Array.isArray(item.meaning)?item.meaning.slice(0,8):[],on:Array.isArray(item.on)?item.on.slice(0,8):[],kun:Array.isArray(item.kun)?item.kun.slice(0,8):[],examples:state.revealed&&Array.isArray(state.examples[item.id])?state.examples[item.id].slice(0,6).map(x=>({word:x.word,reading:x.reading,meaning:x.meaning})):[],hint:rec?'اول خودت معنی یا خوانش را حدس بزن.':'این اولین آشنایی تو با این کانجی است؛ فعلاً فقط آن را یاد بگیر.',revealLabel:rec?'نمایش پاسخ':'نمایش اطلاعات کانجی',contentId:String(item.id||item.character)};}
function notifyV2Learning(){try{window.__KANJI5_V19_V2_BOUNDARY__?.refreshLearning?.()}catch(_) {}}
function directReveal(){if(!state.current)return false;state.revealed=true;const item=state.deck.find(x=>x.id===state.current);if(item)void fetchExamples(item).then(()=>notifyV2Learning());notifyV2Learning();return true}
function directRate(rating){if(!Rating||Rating[rating]===undefined)return false;review(rating);return true}
function updateRuntimeSettings(next={}){state.settings={...state.settings,...next,dailyNew:Math.min(30,Math.max(1,Number(next.dailyNew)||state.settings.dailyNew)),dailyGoal:Math.min(500,Math.max(1,Number(next.dailyGoal)||state.settings.dailyGoal)),leechThreshold:Math.min(30,Math.max(2,Number(next.leechThreshold)||state.settings.leechThreshold))};initScheduler();save();return true}
function renderEmpty(){const remaining=state.deck.filter(k=>!state.cards[k.id]).length;$("study").innerHTML=`<div class="empty"><div style="font-size:58px">✓</div><h2>${remaining?"برای امروز تمام شد.":"دورهٔ ۲۱۳۶ کانجی تمام شد!"}</h2><p>${remaining?"مرورهای انجام‌شده ذخیره شدند؛ فردا ۵ کانجی جدید اضافه می‌شود.":"می‌توانی مرورهایت را ادامه بدهی یا دوره را از تنظیمات بازنشانی کنی."}</p>${!remaining?'<button class="secondary" id="resetInline">شروع دوباره</button>':""}</div>`;$("resetInline")?.addEventListener("click",resetAll)}
let upcomingReviewsTimerStarted=false;function ensureUpcomingReviewsUI(){const studyPanel=$("studyPanel");if(!studyPanel)return null;let panel=$("upcomingReviews");if(panel)return panel;panel=document.createElement('section');panel.id='upcomingReviews';panel.className='panel';panel.style.marginTop='14px';panel.innerHTML='<div style="font-weight:850;font-size:16px;margin-bottom:8px">مرورهای پیش‌رو</div><div id="upcomingReviewsBody" style="color:var(--muted);font-size:13px">—</div>';studyPanel.insertAdjacentElement('afterend',panel);return panel}
function updateUpcomingReviews(){const panel=ensureUpcomingReviewsUI(),body=$("upcomingReviewsBody");if(!panel||!body)return;const now=Date.now();const rows=state.deck.map(item=>{const card=state.cards[item.id]?.card;if(!card?.due)return null;const due=new Date(card.due).getTime();return Number.isFinite(due)&&due>now?{item,due}:null}).filter(Boolean).sort((a,b)=>a.due-b.due).slice(0,6);if(!rows.length){body.textContent='فعلاً مرور زمان‌بندی‌شده‌ای در آینده وجود ندارد.';return}body.innerHTML=rows.map(row=>{const mins=Math.max(1,Math.round((row.due-now)/60000));let when;if(mins<60)when=String(mins)+' دقیقه دیگر';else if(mins<1440)when=String(Math.round(mins/60))+' ساعت دیگر';else when=String(Math.round(mins/1440))+' روز دیگر';return '<div style="display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-top:1px solid var(--line)"><strong>'+row.item.character+'</strong><span>'+when+'</span></div>'}).join('')}
function startUpcomingReviews(){if(upcomingReviewsTimerStarted)return;upcomingReviewsTimerStarted=true;updateUpcomingReviews();setInterval(updateUpcomingReviews,15000)}
function renderCard(){startUpcomingReviews();const id=state.current;if(!id){renderEmpty();updateStats();return}const item=state.deck.find(x=>x.id===id),rec=state.cards[item.id],card=rec?.card;if(card)reviveCard(card);const preview=card?scheduler.repeat(card,new Date()):null;const getPreview=r=>{try{return formatInterval(preview[r].card)}catch(_){return"—"}};$("study").innerHTML=`<div class="kanjirow"><div class="kanji" data-kanji-id="${item.id}">${item.character}</div></div><div class="first-exposure-reading" style="display:${!rec?"block":"none"}"><div class="hira">${(!rec?[...(item.on||[]),...(item.kun||[])].slice(0,3):[]).join(" · ")}</div></div><div style="text-align:center;margin:-6px 0 14px"><button class="audiobtn" id="speakKanjiBtn" aria-label="تلفظ کانجی">🔊 تلفظ</button></div><div class="hint">${rec?"اول خودت معنی یا خوانش را حدس بزن.":"این اولین آشنایی تو با این کانجی است؛ فعلاً فقط آن را یاد بگیر."}</div><button class="reveal" id="revealBtn">${rec?"نمایش پاسخ":"نمایش اطلاعات کانجی"}</button><div class="answer ${state.revealed?'show':''}" id="answerBox"><div class="answerbox"><div class="meaning">${item.meaning.join(" · ")||"—"}</div><div class="readings"><div class="readbox"><div class="t"><span>On'yomi</span>${item.on.length?'<button class="audiobtn" data-speak="'+item.on.join(" ")+'" aria-label="تلفظ آن‌یومی">🔊</button>':""}</div><div class="v reading-list">${item.on.length?item.on.map(r=>`<span class="reading-entry"><span>${r}</span><button class="audiobtn" data-speak="${r}" aria-label="تلفظ خوانش">🔊</button></span>`).join(""):"—"}</div></div><div class="readbox"><div class="t"><span>Kun'yomi</span>${item.kun.length?'<button class="audiobtn" data-speak="'+item.kun.join(" ")+'" aria-label="تلفظ آن‌یومی">🔊</button>':""}</div><div class="v reading-list">${item.kun.length?item.kun.map(r=>`<span class="reading-entry"><span>${r}</span><button class="audiobtn" data-speak="${r}" aria-label="تلفظ خوانش">🔊</button></span>`).join(""):"—"}</div></div></div><div class="examples" id="examples"></div><div class="meta">${formatMeta(item)}</div></div><div class="ratings ${state.revealed?'show':''}" id="ratings"><button class="rate again" data-r="Again">Again<small>${getPreview(Rating.Again)}</small></button><button class="rate hard" data-r="Hard">Hard<small>${getPreview(Rating.Hard)}</small></button><button class="rate good" data-r="Good">Good<small>${getPreview(Rating.Good)}</small></button><button class="rate easy" data-r="Easy">Easy<small>${getPreview(Rating.Easy)}</small></button></div></div>`;
$("revealBtn").addEventListener("click",()=>{if(!window.__KANJI5_CANONICAL_REVEAL__&&rec){window.__KANJI5_V12_OPEN_RECALL__?.();return}if(window.__KANJI5_CANONICAL_REVEAL__)delete window.__KANJI5_CANONICAL_REVEAL__;state.revealed=true;renderCard();fetchExamples(item).then(renderExamples)});
document.querySelectorAll(".rate").forEach(b=>b.addEventListener("click",()=>review(b.dataset.r)));$("speakKanjiBtn")?.addEventListener("click",()=>speak(item.character));document.querySelectorAll("[data-speak]").forEach(b=>b.addEventListener("click",()=>speak(b.dataset.speak)));renderExamples();if(state.revealed)fetchExamples(item).then(renderExamples)}
function renderExamples(){const el=$("examples");if(!el||!state.current)return;const ex=state.examples[state.current]||[];if(!ex.length){el.innerHTML="";return}el.innerHTML=`<h3>نمونه‌های واژگانی</h3><div class="words">${ex.map(x=>`<div class="word"><span>${x.word}</span> <small style="color:#6b7280;direction:ltr;display:inline-block">${x.reading}</small><button class="audiobtn" data-speak="${x.reading||x.word}" aria-label="تلفظ واژه">🔊</button></div>`).join("")}</div>`;el.querySelectorAll("[data-speak]").forEach(b=>b.addEventListener("click",()=>speak(b.dataset.speak)))}
function next(){if(state.queue.length===0){state.current=null;state.revealed=false;if(IS_LEGACY){renderEmpty();updateStats();}notifyV2Learning();return}state.current=state.queue[0];state.revealed=false;if(IS_LEGACY){renderCard();updateStats();}notifyV2Learning()}
function learningBridgeSnapshot(){return reviewSnapshot();}

function resetRuntime(){customStudyFilter=null;try{sessionStorage.removeItem(CUSTOM_STUDY_STORAGE)}catch(_){ }state=window.__KANJI5_STATE__.reset(DEFAULTS,state.deck);initScheduler();buildQueue();next();if(IS_LEGACY)updateStats();notifyV2Learning();return true}
window.__KANJI5_REVIEW_RUNTIME__=Object.freeze({snapshot:reviewSnapshot,reveal:directReveal,rate:directRate,updateSettings:updateRuntimeSettings,reset:resetRuntime,setCustomStudyFilter,clearCustomStudyFilter});
window.__KANJI5_V19_REVIEW_BRIDGE__=Object.freeze({snapshot:reviewSnapshot,setCustomStudyFilter,clearCustomStudyFilter,reveal:(direct=false)=>{if(!IS_LEGACY||direct)return directReveal();const button=document.getElementById('revealBtn');if(!button)return false;window.__KANJI5_CANONICAL_REVEAL__=true;button.click();setTimeout(()=>{delete window.__KANJI5_CANONICAL_REVEAL__},0);setTimeout(notifyV2Learning,0);return true;},rate:(rating)=>{if(!IS_LEGACY)return directRate(rating);const button=document.querySelector(`.rate[data-r="${String(rating||'')}"]`);if(!button)return false;button.click();setTimeout(notifyV2Learning,0);return true;}});

function updateStreak(){const t=todayKey(),s=state.streak;if(s.lastActiveDate===t)return;const y=new Date();y.setDate(y.getDate()-1);const yesterday=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit"}).format(y);s.current=s.lastActiveDate===yesterday?(s.current||0)+1:1;s.longest=Math.max(s.longest||0,s.current);s.lastActiveDate=t}
function review(which){const id=state.current;if(!id)return;const wasNew=!state.cards[id],rec=ensureCard(state.deck.find(x=>x.id===id)),now=new Date(),rating=Rating[which],result=scheduler.next(rec.card,now,rating),beforeState=rec.card.state;rec.card=result.card;rec.reviews=(rec.reviews||0)+1;if(which==="Again")rec.lapses=(rec.lapses||0)+1;if(beforeState===0&&rec.learnedAt===null)rec.learnedAt=now.toISOString();if(rec.lapses>=state.settings.leechThreshold)rec.leech=true;const previousEvent=[...state.reviews].reverse().find(r=>r.id===id&&r.eventId)?.eventId||null;const reviewEventId=eventId();const reviewDeviceId=deviceId();const baseRecord=structuredClone({...rec,card:reviveCard(structuredClone(rec.card))});state.reviews.push({eventId:reviewEventId,deviceId:reviewDeviceId,parentEventId:previousEvent,baseRecord,id,at:now.toISOString(),rating:which,due:rec.card.due,scheduledDays:rec.card.scheduled_days||0});if(state.reviews.length>5000)state.reviews.splice(0,state.reviews.length-5000);if(wasNew)state.todayNew++;state.todayReviewCount=(state.todayReviewCount||0)+1;updateStreak();state.queue.shift();save();const hitGoal=!state.goalCelebrated&&state.todayReviewCount>=state.settings.dailyGoal;if(hitGoal){state.goalCelebrated=true;toast("🎉 هدف روزانه تکمیل شد!")}else if(IS_LEGACY) toast(which==="Again"?"برمی‌گردد برای مرور نزدیک.":"ثبت شد.");next()}
function updateStats(){const due=state.deck.filter(k=>state.cards[k.id]?.card&&dueNow(reviveCard(state.cards[k.id].card))).length,mastered=state.deck.filter(k=>{const c=state.cards[k.id]?.card;return c&&c.state===2&&(c.scheduled_days||0)>=21}).length,studied=state.deck.filter(k=>state.cards[k.id]).length;$("dueCount").textContent=due;$("newCount").textContent=Math.min(state.todayNew,state.settings.dailyNew);$("masteredCount").textContent=mastered;$("bar").style.width=`${state.deck.length?Math.round(studied/state.deck.length*100):0}%`;$("streakCount").textContent=`${state.streak.current||0}🔥`;const goalDone=Math.min(state.todayReviewCount||0,state.settings.dailyGoal);$("goalLabel").textContent=`هدف روزانه: ${state.todayReviewCount||0}/${state.settings.dailyGoal}`;$("goalBar").style.width=`${Math.round(goalDone/state.settings.dailyGoal*100)}%`;$("goalDone").style.display=(state.todayReviewCount||0)>=state.settings.dailyGoal?"inline":"none"}
function resetAll(){if(!confirm("تمام پیشرفت‌ها پاک شود؟"))return;localStorage.removeItem(STORAGE);localStorage.removeItem(CARDS_STORAGE);localStorage.removeItem(REVIEWS_STORAGE);state=window.__KANJI5_STATE__.reset(DEFAULTS,state.deck);initScheduler();buildQueue();next();updateStats();toast("پیشرفت پاک شد.")}
if(IS_LEGACY){
$("settingsBtn").addEventListener("click",()=>{$("dailyNew").value=state.settings.dailyNew;$("dailyGoal").value=state.settings.dailyGoal;$("leechThreshold").value=state.settings.leechThreshold;$("settingsDialog").showModal()});
$("closeSettings").addEventListener("click",()=>$("settingsDialog").close());
$("saveSettings").addEventListener("click",()=>{state.settings.dailyNew=Math.min(30,Math.max(1,Number($("dailyNew").value)||5));state.settings.dailyGoal=Math.min(500,Math.max(1,Number($("dailyGoal").value)||20));state.settings.leechThreshold=Math.min(30,Math.max(2,Number($("leechThreshold").value)||8));initScheduler();save();$("settingsDialog").close();buildQueue();next();updateStats()});
$("resetBtn").addEventListener("click",resetAll);
function renderStats(){const total=state.reviews.length,correct=state.reviews.filter(r=>r.rating!=="Again").length,accuracy=total?Math.round(correct/total*100):0,leechCount=Object.values(state.cards).filter(c=>c.leech).length,studied=state.deck.filter(k=>state.cards[k.id]).length,stateNames=["جدید (New)","یادگیری (Learning)","مرور (Review)","بازآموزی (Relearning)"],stateCounts=[0,0,0,0];for(const c of Object.values(state.cards)){const s=c.card?.state;if(s!=null&&stateCounts[s]!=null)stateCounts[s]++}const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit"}).format(d),label=new Intl.DateTimeFormat("fa-IR",{weekday:"short"}).format(d),count=state.reviews.filter(r=>r.at.slice(0,10)===key).length;days.push({label,count})}const maxDay=Math.max(1,...days.map(d=>d.count));$("statsBody").innerHTML=`<div class="statsgrid"><div class="box"><div class="n">${total}</div><div class="l">کل مرورها</div></div><div class="box"><div class="n">${accuracy}%</div><div class="l">دقت (غیر از Again)</div></div><div class="box"><div class="n">${studied}/${state.deck.length}</div><div class="l">کانجی مطالعه‌شده</div></div><div class="box"><div class="n">${state.streak.longest||0}🔥</div><div class="l">طولانی‌ترین رشته</div></div><div class="box"><div class="n">${leechCount}</div><div class="l">Leech (کانجی دشوار)</div></div><div class="box"><div class="n">${state.streak.current||0}</div><div class="l">رشتهٔ فعلی (روز)</div></div></div><h3 style="font-size:14px;color:var(--muted);margin:14px 0 4px">مرورهای ۷ روز اخیر</h3><div class="bars">${days.map(d=>`<div class="col"><div class="fill" style="height:${Math.round(d.count/maxDay*80)+2}px"></div><div class="lbl">${d.label}<br>${d.count}</div></div>`).join('')}</div><h3 style="font-size:14px;color:var(--muted);margin:14px 0 4px">وضعیت کارت‌ها</h3><div class="statesrow">${stateNames.map((n,i)=>`<span class="chip">${n}: ${stateCounts[i]}</span>`).join('')}</div>`;}
$("statsBtn").addEventListener("click",()=>{renderStats();$("statsDialog").showModal()});
$("closeStats").addEventListener("click",()=>$("statsDialog").close());
document.addEventListener("keydown",e=>{if(document.querySelector("dialog[open]")||!state.current)return;if(!state.revealed&&(e.code==="Space"||e.key==="Enter")){e.preventDefault();$("revealBtn")?.click();return}if(state.revealed){const map={"1":"Again","2":"Hard","3":"Good","4":"Easy"};if(map[e.key])document.querySelector(`.rate[data-r="${map[e.key]}"]`)?.click()}});
}
async function start(){try{const shared=window.__KANJI5_P0_FSRS_PROMISE;const loadPromise=shared?shared.then(mod=>{if(!mod)throw new Error("FSRS_PREFETCH_FAILED");return mod}):import(FSRS_URL);const mod=await Promise.race([loadPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error("FSRS_LOAD_TIMEOUT")),10000))]);({createEmptyCard,fsrs,Rating}=mod);}catch(e){console.error(e);if(IS_LEGACY){$("loading").innerHTML="<div><div style=\"font-size:42px\">⚠️</div><div style=\"font-weight:800;margin:10px 0\">موتور مرور بارگذاری نشد.</div><div style=\"color:#6b7280;font-size:13px;line-height:1.8\">اتصال به کتابخانه مرور برقرار نشد. اتصال اینترنت را بررسی کن و دوباره تلاش کن.</div><button class=\"primary\" id=\"v12FsrsRetry\" style=\"margin-top:14px\">تلاش دوباره</button></div>";$("v12FsrsRetry").addEventListener("click",()=>location.reload());return;}}state=loadSaved(state,DEFAULTS);state=hydrateCards(state);customStudyCore=await import('./v2-custom-study-core.js');if(customStudyFilter)customStudyFilter=customStudyCore.normalizeCustomStudyFilter(customStudyFilter);const cached=loadDeckFromCache();try{if(!cached)await loadDeck();initScheduler();if(IS_LEGACY){$("loading").hidden=true;$("app").hidden=false;}buildQueue();next();if(IS_LEGACY)updateStats()}catch(e){console.error(e);if(IS_LEGACY){$("loadStatus").innerHTML=`بارگذاری داده ممکن نشد.<br><br><button class="primary" id="retry">تلاش دوباره</button>`;$("retry").addEventListener("click",()=>location.reload())}}}start();
