const CACHE='kanji5-shell-v22';
const DATA_CACHE='kanji5-data-v14';
const API_CACHE='kanji5-api-v5';
const SHELL=['./','./index.html','./manifest.webmanifest','./icon.svg','./v1.3-p0.js','./v1.3-p1.js','./v1.3-dont-know.js','./v1.3-perf.js','./v1.2-enhancements.js','./v1.2-runtime-fixes.js','./supabase-config.js','./supabase-sync.js'];
const DATA_URL=new URL('./kanji-data.json',self.location.href).href;
const API_ORIGIN='https://kanjiapi.dev';
self.addEventListener('install',e=>e.waitUntil(Promise.all([caches.open(CACHE).then(c=>c.addAll(SHELL)),caches.open(DATA_CACHE).then(c=>c.add('./kanji-data.json')),caches.open(API_CACHE)]).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('kanji5-')&&![CACHE,DATA_CACHE,API_CACHE].includes(k)).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function cacheFirst(req,name,fallback=req){const c=await caches.open(name),hit=await c.match(fallback);if(hit)return hit;try{const r=await fetch(req);if(r.ok)await c.put(req,r.clone());return r}catch(_){return(await c.match(fallback))||Response.error()}}
async function networkFirst(req,name,fallback=req){const c=await caches.open(name);try{const r=await fetch(req);if(r.ok)await c.put(req,r.clone());return r}catch(_){return(await c.match(fallback))||Response.error()}}
async function apiCacheFirst(req){const c=await caches.open(API_CACHE),hit=await c.match(req);if(hit)return hit;try{const r=await fetch(req);if(r.ok||r.type==='opaque')await c.put(req,r.clone());return r}catch(_){return(await c.match(req))||Response.error()}}
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(r.mode==='navigate'){e.respondWith((async()=>{const res=await networkFirst(r,CACHE,'./index.html');try{let html=await res.text();let out=html;
if(!out.includes('src="./v1.3-p0.js"'))out=out.replace('<script type="module">','<script src="./v1.3-p0.js"></script><script type="module">');
if(!out.includes('src="./v1.3-dont-know.js"'))out=out.replace('<script src="./v1.3-p1.js"></script>','<script src="./v1.3-p1.js"></script><script src="./v1.3-dont-know.js"></script>');
if(!out.includes('src="./v1.3-perf.js"'))out=out.replace('<script src="./v1.3-p1.js"></script>','<script src="./v1.3-p1.js"></script><script src="./v1.3-perf.js"></script>');
out=out.replace('const mod=await Promise.race([import(FSRS_URL),new Promise((_,reject)=>setTimeout(()=>reject(new Error("FSRS_LOAD_TIMEOUT")),10000))]);','const mod=await Promise.race([window.__KANJI5_P0_FSRS_PROMISE||import(FSRS_URL),new Promise((_,reject)=>setTimeout(()=>reject(new Error("FSRS_LOAD_TIMEOUT")),10000))]);');
out=out.replace(/<script id="v1\.2-loading-watchdog">[\s\S]*?<\/script>/,'');
out=out.replace('async function loadDeck(){\n  $("loadStatus").textContent="در حال دریافت فهرست Jōyō...";\n  const res=await fetch(DATA_URL,{cache:"force-cache"});\n  if(!res.ok)throw new Error("Could not load local kanji dataset");\n  const data=await res.json();\n  const all=Array.isArray(data)?data:(data.kanji||[]);','async function loadDeck(){\n  const data=window.__KANJI5_P0_DATA || await window.__KANJI5_P0_DATA_PROMISE;\n  if(!Array.isArray(data))throw new Error("Could not load local kanji dataset");\n  const all=data;');
out=out.replace('state.deck=all;\n  localStorage.setItem("kanji5-deck",JSON.stringify(state.deck));','state.deck=all;');
out=out.replace('function loadDeckFromCache(){try{const x=JSON.parse(localStorage.getItem("kanji5-deck")||"null");if(Array.isArray(x)&&x.length===2136){state.deck=x;return true}}catch(_){}return false}','async function loadDeckFromCache(){return false}');
out=out.replace('const cached=loadDeckFromCache();try{if(!cached)await loadDeck();','const cached=await loadDeckFromCache();try{if(!cached)await loadDeck();');
out=out.replace('function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}','function save(){const snapshot={...state};delete snapshot.deck;try{localStorage.setItem(STORAGE,JSON.stringify(snapshot))}catch(_){}}');
out=out.replace('function rebuildStatsCache(){let due=0,mastered=0,studied=0;for(const k of state.deck){const rec=state.cards[k.id];if(rec)studied++;const c=rec?.card;if(c&&dueNow(reviveCard(c)))due++;if(c&&c.state===2&&(c.scheduled_days||0)>=21)mastered++;}state._stats={due,mastered,studied}}\nfunction updateStats(){const stats=state._stats||{due:0,mastered:0,studied:0};const due=stats.due,mastered=stats.mastered,studied=stats.studied;','function rebuildStatsCache(){let due=0,mastered=0,studied=0;for(const k of state.deck){const rec=state.cards[k.id];if(rec)studied++;const c=rec?.card;if(c&&dueNow(reviveCard(c)))due++;if(c&&c.state===2&&(c.scheduled_days||0)>=21)mastered++;}state._stats={due,mastered,studied}}\nfunction updateStats(){const stats=state._stats||{due:0,mastered:0,studied:0};const due=stats.due,mastered=stats.mastered,studied=stats.studied;');
out=out.replace('if(!state._stats)rebuildStatsCache();state._stats.studied+=wasNew?1:0;state._stats.due=Math.max(0,state._stats.due-(wasNew?0:1));state.queue.shift();save();const hitGoal=','if(!state._stats)rebuildStatsCache();const beforeDue=!wasNew&&dueNow(rec.card);const beforeMastered=!wasNew&&rec.card?.state===2&&(rec.card?.scheduled_days||0)>=21;const afterDue=dueNow(rec.card);const afterMastered=rec.card?.state===2&&(rec.card?.scheduled_days||0)>=21;if(wasNew)state._stats.studied++;if(beforeDue!==afterDue)state._stats.due+=afterDue?1:-1;if(beforeMastered!==afterMastered)state._stats.mastered+=afterMastered?1:-1;state.queue.shift();save();const hitGoal=');
out=out.replace('initScheduler();$("loading").hidden=true;','initScheduler();rebuildStatsCache();$("loading").hidden=true;');
out=out.replace('initScheduler();buildQueue();next();updateStats();toast("پیشرفت پاک شد.")','initScheduler();rebuildStatsCache();buildQueue();next();updateStats();toast("پیشرفت پاک شد.")');
if(out!==html){const h=new Headers(res.headers);h.delete('content-length');h.set('cache-control','no-cache');return new Response(out,{status:res.status,statusText:res.statusText,headers:h})}}catch(_){}return res})());return}if(u.origin===API_ORIGIN&&u.pathname.startsWith('/v1/words/')){e.respondWith(apiCacheFirst(r));return}if(u.origin!==self.location.origin)return;if(u.href===DATA_URL){e.respondWith(cacheFirst(r,DATA_CACHE,'./kanji-data.json'));return}e.respondWith(caches.match(r).then(hit=>hit||fetch(r).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(r,res.clone()));return res})))})