(()=>{
'use strict';
const KEY='kanji5-v1', KNOW='kanji5-v1.2-knowledge', SETTINGS='kanji5-v1.3-education-settings';
const WORDS=ch=>'https://kanjiapi.dev/v1/words/'+encodeURIComponent(ch);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DEFAULTS={production:true,vocabulary:true,context:true};
let active=null,cache=new Map(),deckMap=null;
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFKC').replace(/[\s\u3000]+/g,'');
const hiraPairs=[['きゃ','kya'],['きゅ','kyu'],['きょ','kyo'],['しゃ','sha'],['しゅ','shu'],['しょ','sho'],['ちゃ','cha'],['ちゅ','chu'],['ちょ','cho'],['にゃ','nya'],['にゅ','nyu'],['にょ','nyo'],['ひゃ','hya'],['ひゅ','hyu'],['ひょ','hyo'],['みゃ','mya'],['みゅ','myu'],['みょ','myo'],['りゃ','rya'],['りゅ','ryu'],['りょ','ryo'],['ぎゃ','gya'],['ぎゅ','gyu'],['ぎょ','gyo'],['じゃ','ja'],['じゅ','ju'],['じょ','jo'],['びゃ','bya'],['びゅ','byu'],['びょ','byo'],['ぴゃ','pya'],['ぴゅ','pyu'],['ぴょ','pyo'],['あ','a'],['い','i'],['う','u'],['え','e'],['お','o'],['か','ka'],['き','ki'],['く','ku'],['け','ke'],['こ','ko'],['さ','sa'],['し','shi'],['す','su'],['せ','se'],['そ','so'],['た','ta'],['ち','chi'],['つ','tsu'],['て','te'],['と','to'],['な','na'],['に','ni'],['ぬ','nu'],['ね','ne'],['の','no'],['は','ha'],['ひ','hi'],['ふ','fu'],['へ','he'],['ほ','ho'],['ま','ma'],['み','mi'],['む','mu'],['め','me'],['も','mo'],['や','ya'],['ゆ','yu'],['よ','yo'],['ら','ra'],['り','ri'],['る','ru'],['れ','re'],['ろ','ro'],['わ','wa'],['を','o'],['ん','n'],['が','ga'],['ぎ','gi'],['ぐ','gu'],['げ','ge'],['ご','go'],['ざ','za'],['じ','ji'],['ず','zu'],['ぜ','ze'],['ぞ','zo'],['だ','da'],['ぢ','ji'],['づ','zu'],['で','de'],['ど','do'],['ば','ba'],['び','bi'],['ぶ','bu'],['べ','be'],['ぼ','bo'],['ぱ','pa'],['ぴ','pi'],['ぷ','pu'],['ぺ','pe'],['ぽ','po'],['ゔ','vu']];
const hm=new Map(hiraPairs);
function hiraToRomaji(v){let s=String(v||'').normalize('NFKC').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)),o='';for(let i=0;i<s.length;){if(s[i]==='っ'){const n=hm.get(s.slice(i+1,i+3))||hm.get(s[i+1])||'';if(n&&/^[bcdfghjklmnpqrstvwxyz]/.test(n))o+=n[0];i++;continue}const p=s.slice(i,i+2);if(hm.has(p)){o+=hm.get(p);i+=2}else{o+=hm.get(s[i])||s[i];i++}}return o}
function normRomaji(v){return norm(v).replace(/[^a-z]/g,'').replace(/si/g,'shi').replace(/ti/g,'chi').replace(/tu/g,'tsu').replace(/hu/g,'fu').replace(/zi/g,'ji').replace(/du/g,'zu').replace(/di/g,'ji').replace(/wo/g,'o')}
function settings(){try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(SETTINGS)||'{}')}}catch(_){return{...DEFAULTS}}}
function saveSettings(v){try{localStorage.setItem(SETTINGS,JSON.stringify({...DEFAULTS,...v}))}catch(_){} }
window.KANJI5_EDUCATION_SETTINGS={read:settings,write:saveSettings,defaults:{...DEFAULTS}};
function ensureSettingsUI(){const d=$('#settingsDialog'),m=d&&$('.modal',d);if(!m||$('#v13EducationSettings',m))return;const s=document.createElement('section');s.id='v13EducationSettings';s.innerHTML='<h3 style="font-size:15px;margin:20px 0 8px">قابلیت‌های آموزشی</h3><div style="color:var(--muted);font-size:12px;line-height:1.6;margin-bottom:10px">تمرین‌های پیشرفته را می‌توانی جداگانه فعال یا غیرفعال کنی.</div><label class="setting"><span>تولید کانجی (Kanji Production)</span><input id="v13Production" type="checkbox"></label><label class="setting"><span>تکمیل واژه (Vocabulary Completion)</span><input id="v13Vocabulary" type="checkbox"></label><label class="setting"><span>یادآوری بافت واژه (Context Recall)</span><input id="v13Context" type="checkbox"></label>';const row=$('#resetBtn',m)?.closest('.setting');(row||$('.setting',m))?.before(s);const x=settings();$('#v13Production').checked=!!x.production;$('#v13Vocabulary').checked=!!x.vocabulary;$('#v13Context').checked=!!x.context;['v13Production','v13Vocabulary','v13Context'].forEach(id=>$('#'+id)?.addEventListener('change',()=>saveSettings({production:!!$('#v13Production')?.checked,vocabulary:!!$('#v13Vocabulary')?.checked,context:!!$('#v13Context')?.checked})));}
document.addEventListener('DOMContentLoaded',ensureSettingsUI,{once:true});document.getElementById('settingsBtn')?.addEventListener('click',()=>setTimeout(ensureSettingsUI,0));
function knowledge(){try{return JSON.parse(localStorage.getItem(KNOW)||'{}')}catch(_){return{}}}
function record(ch,mode,ok){const all=knowledge(),n=all[ch]||{},x=n[mode]||{attempts:0,correct:0};x.attempts++;if(ok)x.correct++;x.lastAt=new Date().toISOString();n[mode]=x;n.lastPrompt=mode;all[ch]=n;try{localStorage.setItem(KNOW,JSON.stringify(all))}catch(_){} }
function mastery(ch,mode){const x=(knowledge()[ch]||{})[mode]||{attempts:0,correct:0};return(x.correct+1)/(x.attempts+2)}
function current(){const el=$('.kanji'),ch=el?.textContent?.trim();if(!ch)return null;if(!deckMap){try{const d=JSON.parse(localStorage.getItem('kanji5-deck')||'[]');deckMap=new Map((Array.isArray(d)?d:[]).map(x=>[x.character,x]))}catch(_){deckMap=new Map()}}return{ch,item:deckMap.get(ch),id:el.dataset.kanjiId}}
function firstExposure(){const c=current();if(!c?.id)return false;try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return!x?.cards?.[c.id]}catch(_){return false}}
async function getWords(ch){if(cache.has(ch))return cache.get(ch);let a=[];try{const r=await fetch(WORDS(ch),{cache:'force-cache'});if(r.ok){const d=await r.json(),seen=new Set();for(const e of(Array.isArray(d)?d:[])){for(const v of(e.variants||[])){const w=v.written||'',rd=v.pronounced||'';if(w.includes(ch)&&rd&&!seen.has(w)){seen.add(w);a.push({word:w,reading:rd,meaning:(e.meanings||[]).flatMap(m=>m.glosses||[]).slice(0,2).join('; ')})}if(a.length>=8)break}if(a.length>=8)break}}}catch(_){}cache.set(ch,a);return a}
function chooseMode(ch,hasWords){const s=settings(),m=['meaning','reading'];if(s.production)m.push('production');if(hasWords&&s.vocabulary)m.push('vocabulary');if(hasWords&&s.context)m.push('context');const n=knowledge()[ch]||{};const fresh=m.filter(x=>!(n[x]?.attempts));return fresh[0]||m.sort((a,b)=>mastery(ch,a)-mastery(ch,b))[0]||'meaning'}
function choices(target){let a=[];try{a=JSON.parse(localStorage.getItem('kanji5-deck')||'[]')}catch(_){}const pool=(Array.isArray(a)?a:[]).map(x=>x.character).filter(x=>x&&x!==target);const out=[target];while(pool.length&&out.length<4){out.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0])}return out.sort(()=>Math.random()-.5)}
function finish(ok){if(!active)return;const{ch,item,mode}=active;record(ch,mode,ok);const gate=$('.v13-p1-gate');if(!gate)return;gate.innerHTML='<div class="v13-p1-card"><div class="v13-p1-title">'+(ok?'✅ پاسخ درست بود':'❌ پاسخ درست نبود')+'</div><div class="v13-p1-answer">پاسخ صحیح: <strong>'+(mode==='meaning'?(item.meaning||[]).join(' · '):mode==='reading'?[...(item.on||[]),...(item.kun||[])].join(' · '):ch)+'</strong></div><button id="v13P1RevealAnswer" class="primary" style="width:100%;margin-top:12px">نمایش پاسخ کامل</button></div>'}
function showAnswer(){$('.v13-p1-gate')?.remove();$('#answerBox')?.classList.add('show');$('#ratings')?.classList.add('show');active=null}
async function openGate(){const c=current();if(!c?.item)return false;const ws=await getWords(c.ch),mode=chooseMode(c.ch,ws.length>0);active={...c,mode,words:ws};const b=$('#revealBtn');if(!b)return false;const g=document.createElement('div');g.className='v13-p1-gate';g.innerHTML='<div class="v13-p1-card"><div class="v13-p1-title">🧠 تمرین یادآوری</div><div id="v13P1Prompt" class="v13-p1-prompt"></div><div id="v13P1Body"></div><button id="v13P1Submit" class="primary" style="width:100%;margin-top:10px">بررسی پاسخ</button></div>';b.replaceWith(g);const p=$('#v13P1Prompt'),body=$('#v13P1Body'),i=c.item;if(mode==='meaning'){p.textContent='حداقل یک معنی این کانجی را از حافظه بنویس.';body.innerHTML='<input id="v13P1Input" class="v13-p1-input" autocomplete="off" spellcheck="false" placeholder="مثلاً: school">'}else if(mode==='reading'){p.textContent='یک خوانش رایج را از حافظه بنویس؛ Hiragana یا Romaji هر دو قابل قبول‌اند.';body.innerHTML='<input id="v13P1Input" class="v13-p1-input" autocomplete="off" spellcheck="false" placeholder="مثلاً: gaku یا がく">'}else if(mode==='production'){p.innerHTML='معنی: <strong>'+((i.meaning||[]).join(' · ')||'—')+'</strong><br>کانجی مناسب را انتخاب کن.';body.innerHTML='<div class="v13-production-choices" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px">'+choices(c.ch).map(x=>'<button type="button" class="secondary v13-production-choice" data-choice="'+x+'" style="font-family:serif;font-size:38px;padding:14px 8px;min-height:78px">'+x+'</button>').join('')+'</div>'}else{const w=ws[0];if(!w)return false;active.word=w;if(mode==='vocabulary'){p.textContent='کانجی گمشده را در این واژه کامل کن.';body.innerHTML='<div class="v13-p1-word">'+w.word.replace(c.ch,'＿')+'</div><div class="v13-p1-reading">'+w.reading+'</div><input id="v13P1Input" class="v13-p1-input v13-p1-kanji" maxlength="2" placeholder="کانجی گمشده">'}else{p.textContent='از روی بافت واژه، کانجی را به یاد بیاور.';body.innerHTML='<div class="v13-p1-reading">خوانش: '+w.reading+'</div>'+(w.meaning?'<div class="v13-p1-word-meaning">'+w.meaning+'</div>':'')+'<input id="v13P1Input" class="v13-p1-input v13-p1-kanji" maxlength="2" placeholder="کانجی">'}}if(mode==='production')$$('.v13-production-choice',g).forEach(x=>x.addEventListener('click',()=>{const ok=x.dataset.choice===active.ch;$$('.v13-production-choice',g).forEach(y=>y.disabled=true);finish(ok)}));else setTimeout(()=>$('#v13P1Input')?.focus(),0);return true}
function submit(){if(!active)return;const v=$('#v13P1Input')?.value||'';if(!norm(v)){$('#v13P1Input')?.focus();return}const{ch,item,mode,word}=active;let ok=false;if(mode==='meaning'){const a=norm(v);ok=(item.meaning||[]).some(x=>{const c=norm(x);return c&&(a===c||a.includes(c)||c.includes(a))})}else if(mode==='reading'){const a=norm(v),r=normRomaji(v);ok=[...(item.on||[]),...(item.kun||[])].some(x=>a===norm(x)||r===normRomaji(hiraToRomaji(x)))}else if(mode==='production')ok=v===ch;else ok=!!word&&v===ch;finish(ok)}
document.addEventListener('click',e=>{const t=e.target;if(t?.id==='revealBtn'&&!firstExposure()){e.preventDefault();e.stopImmediatePropagation();void openGate();return}if(t?.id==='v13P1Submit'){e.preventDefault();e.stopImmediatePropagation();submit();return}if(t?.id==='v13P1RevealAnswer'){e.preventDefault();e.stopImmediatePropagation();showAnswer()}},true);
document.addEventListener('keydown',e=>{if(e.target?.id==='v13P1Input'&&e.key==='Enter'){e.preventDefault();submit()}} ,true);
})();