(()=>{
'use strict';
if(window.__KANJI5_V15_P0__)return;
window.__KANJI5_V15_P0__=true;
const COMPONENT_KEY='kanji5-v1.5-components';
const $=(selector,root=document)=>root.querySelector(selector);
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);if(!raw)return fallback;const value=JSON.parse(raw);return value&&typeof value==='object'?value:fallback}catch(_){return fallback}}
function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(_) {}}
function normalize(value){return String(value==null?'':value).trim().toLowerCase().normalize('NFKC').replace(/[\s\u3000]+/g,'')}
function getDeck(){return Array.isArray(window.__KANJI5_P0_DATA)?window.__KANJI5_P0_DATA:[]}
function ensureComponentEntry(character){const all=readJSON(COMPONENT_KEY,{});if(!all[character]||typeof all[character]!=='object')all[character]={meaning:{},reading:{},updatedAt:null};if(!all[character].meaning||typeof all[character].meaning!=='object')all[character].meaning={};if(!all[character].reading||typeof all[character].reading!=='object')all[character].reading={};return all}
function componentAccuracy(stats){const attempts=Math.max(0,Number(stats?.attempts)||0),correct=Math.min(attempts,Math.max(0,Number(stats?.correct)||0));if(!attempts)return 0;const score=Number.isFinite(Number(stats?.score))?Math.max(0,Math.min(attempts,Number(stats.score))):correct;return(score+1)/(attempts+2)}
function getFocusComponent(character,mode){const item=getDeck().find(entry=>entry&&entry.character===character);if(!item)return null;const state=ensureComponentEntry(character)[character][mode],values=mode==='reading'?[...(item.on||[]),...(item.kun||[])]:[...(item.meaning||[])],candidates=values.map(raw=>({raw,key:normalize(raw),accuracy:componentAccuracy(state[normalize(raw)]||{})}));candidates.sort((a,b)=>a.accuracy-b.accuracy);return candidates[0]||null}
function gradeFocusedRecall(mode,answer,focus){const core=window.__KANJI5_EDU_CORE__;if(!core||!focus)return false;return mode==='reading'?Boolean(core.gradeReading(answer,[focus.raw]).correct):Boolean(core.gradeMeaning(answer,[focus.raw]).correct)}
function recordFocusedRecall(character,mode,focus,outcome){const all=ensureComponentEntry(character),bucket=all[character][mode],key=normalize(focus),stats=bucket[key]||{attempts:0,correct:0,unknown:0,score:0,lastAt:null};stats.attempts+=1;if(outcome==='correct'){stats.correct+=1;stats.score+=1}else if(outcome==='unknown'){stats.unknown=(Number(stats.unknown)||0)+1;stats.score+=.25}stats.lastAt=new Date().toISOString();bucket[key]=stats;all[character].updatedAt=stats.lastAt;writeJSON(COMPONENT_KEY,all)}
function enhanceRecall(){const gate=$('.v12-recall-gate'),kanji=$('.kanji');if(!gate||!kanji)return;const character=String(kanji.textContent||'').trim();if(!character||gate.dataset.v15Ready===character)return;const mode=String(gate.textContent||'').includes('خوانش')?'reading':'meaning',focus=getFocusComponent(character,mode);if(!focus)return;gate.dataset.v15Ready=character;gate.dataset.v15Mode=mode;gate.dataset.v15Focus=focus.raw;const prompt=[...gate.querySelectorAll('div')].find(node=>{const text=String(node.textContent||'').trim();return text.includes('معنی این کانجی')||text.includes('حداقل یک خوانش')});if(prompt)prompt.textContent=mode==='meaning'?`معنی هدف: «${focus.raw}» — سعی کن همین معنی را از حافظه به یاد بیاوری.`:`خوانش هدف: «${focus.raw}» — سعی کن همین خوانش را از حافظه به یاد بیاوری.`}
function recordRecall(event){const gate=event.target?.closest?.('.v12-recall-gate'),button=event.target?.closest?.('button');if(!gate||!button||button.id==='v15DontKnowRecall')return;const kanji=$('.kanji'),input=gate.querySelector('input,textarea');if(!kanji||!input)return;const character=String(kanji.textContent||'').trim(),answer=String(input.value||'').trim(),mode=gate.dataset.v15Mode||'meaning',focus=gate.dataset.v15Focus||'';if(!character||!answer||!focus)return;recordFocusedRecall(character,mode,focus,gradeFocusedRecall(mode,answer,{raw:focus})?'correct':'wrong')}
function revealAfterUnknown(gate){const answer=gate.closest?.('#study')?.querySelector?.('.answer')||$('.answer'),answerBox=$('#answerBox'),ratings=$('#ratings');if(answer)answer.classList.add('show');if(answerBox)answerBox.classList.add('show');if(ratings){ratings.style.display='grid';ratings.classList.add('show')}gate.remove()}
function addDontKnowRecall(){const gate=$('.v12-recall-gate');if(!gate||$('#v15DontKnowRecall',gate))return;const input=gate.querySelector('input,textarea');if(!input)return;const button=document.createElement('button');button.type='button';button.id='v15DontKnowRecall';button.className='secondary';button.textContent='نمی‌دانم';button.addEventListener('click',()=>{const kanji=$('.kanji'),character=String(kanji?.textContent||'').trim(),mode=gate.dataset.v15Mode||'meaning',focus=gate.dataset.v15Focus||'';if(character&&focus){recordFocusedRecall(character,mode,focus,'unknown');try{localStorage.setItem('kanji5-v1.2-last-attempt',JSON.stringify({character,mode,attemptedAt:new Date().toISOString(),hadAttempt:true,correct:false,unknown:true}))}catch(_) {}}const result=gate.querySelector('.v12-recall-result');if(result){result.className='v12-recall-result unknown';result.textContent='این مورد را نمی‌دانستم'}revealAfterUnknown(gate)});input.parentElement?.appendChild(button)}
function startTargetedObservers(){const studyRoot=$('#studyPanel')||$('#study');if(studyRoot){const observer=new MutationObserver(()=>{enhanceRecall();addDontKnowRecall()});observer.observe(studyRoot,{childList:true,subtree:true})}enhanceRecall();addDontKnowRecall()}
document.addEventListener('click',recordRecall,true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startTargetedObservers,{once:true});else startTargetedObservers();
})();