(()=>{
'use strict';
if(window.__KANJI5_STATE__)return;
const DEVICE_KEY='kanji5-device-id',STORAGE='kanji5-v1',CARDS_STORAGE='kanji5-v1-cards',REVIEWS_STORAGE='kanji5-v1-reviews',REVIEW_EVENT_SCHEMA_VERSION=2;
const defaults={dailyNew:5,retention:.90,maxInterval:36500,dailyGoal:20,leechThreshold:8};
let activeState=null;
const todayKey=()=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function deviceId(){try{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,id)}return id}catch(_){return'legacy'}}
function eventId(){return crypto.randomUUID?.()||`review-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function createInitial(overrides={}){const created={settings:{...defaults,...(overrides.settings||{})},deck:Array.isArray(overrides.deck)?overrides.deck:[],cards:overrides.cards&&typeof overrides.cards==='object'?overrides.cards:{},reviews:Array.isArray(overrides.reviews)?overrides.reviews:[],today:overrides.today||'',todayNew:Number(overrides.todayNew)||0,todayReviewCount:Number(overrides.todayReviewCount)||0,goalCelebrated:Boolean(overrides.goalCelebrated),queue:Array.isArray(overrides.queue)?overrides.queue:[],current:overrides.current||null,revealed:Boolean(overrides.revealed),examples:overrides.examples&&typeof overrides.examples==='object'?overrides.examples:{},streak:{current:0,longest:0,lastActiveDate:null,...(overrides.streak||{})}};activeState=created;return created}
function normalizeReviewEvent(event){if(!event||typeof event!=='object')return event;const normalized={...event};if(!normalized.eventSchemaVersion)normalized.eventSchemaVersion=1;if(normalized.eventSchemaVersion===1&&normalized.baseRecord&&!normalized.resultRecord)normalized.resultRecord=structuredClone(normalized.baseRecord);return normalized}
function compactReviews(reviews){const source=Array.isArray(reviews)?reviews.map(normalizeReviewEvent).filter(Boolean):[];return source.slice(-2000)}
function save(state=activeState){if(!state||typeof state!=='object')return;activeState=state;const cards=state.cards&&typeof state.cards==='object'?state.cards:{};const metadata={settings:state.settings,today:state.today,todayNew:state.todayNew,todayReviewCount:state.todayReviewCount,goalCelebrated:state.goalCelebrated,streak:state.streak,cards};const reviews=compactReviews(state.reviews);state.reviews=reviews;const persist=(reviewLimit)=>{const nextReviews=reviews.slice(-reviewLimit);localStorage.setItem(STORAGE,JSON.stringify(metadata));localStorage.setItem(CARDS_STORAGE,JSON.stringify(cards));localStorage.setItem(REVIEWS_STORAGE,JSON.stringify(nextReviews));state.reviews=nextReviews};try{persist(reviews.length)}catch(error){try{persist(Math.min(reviews.length,500))}catch(_){try{localStorage.setItem(STORAGE,JSON.stringify(metadata));localStorage.setItem(CARDS_STORAGE,JSON.stringify(cards))}catch(_){}}}}
function loadSaved(state,defaultsValue=defaults){try{const raw=localStorage.getItem(STORAGE),x=raw?JSON.parse(raw):null,cardsRaw=localStorage.getItem(CARDS_STORAGE),reviewsRaw=localStorage.getItem(REVIEWS_STORAGE);if(!raw){const next={...state,today:todayKey()};activeState=next;return next}const cards=cardsRaw?JSON.parse(cardsRaw):(x?.cards||{}),reviews=reviewsRaw?JSON.parse(reviewsRaw):(x?.reviews||[]);const next={...state,...x,cards,reviews:reviews.map(normalizeReviewEvent),settings:{...defaultsValue,...(x.settings||{})},streak:{current:0,longest:0,lastActiveDate:null,...(x.streak||{})}};if(next.today!==todayKey()){next.today=todayKey();next.todayNew=0;next.todayReviewCount=0;next.goalCelebrated=false}activeState=next;return next}catch(_){const next={...state,today:todayKey()};activeState=next;return next}}
function reviveCard(card){if(!card)return null;const out=structuredClone(card);for(const key of ['due','last_review'])if(out[key])out[key]=new Date(out[key]);return out}
function hydrateCards(state){for(const id of Object.keys(state.cards||{}))if(state.cards[id])state.cards[id].card=reviveCard(state.cards[id].card);activeState=state;return state}
function reset(defaultsValue,deck=[]){return createInitial({settings:{...defaultsValue},deck,today:todayKey()})}
window.__KANJI5_STATE__=Object.freeze({DEFAULTS:Object.freeze({...defaults}),STORAGE,CARDS_STORAGE,REVIEWS_STORAGE,REVIEW_EVENT_SCHEMA_VERSION,todayKey,deviceId,eventId,createInitial,normalizeReviewEvent,save,loadSaved,reviveCard,hydrateCards,reset});
})();
