(()=>{
'use strict';
if(window.__KANJI5_V15_P0__)return;
window.__KANJI5_V15_P0__=true;
const COMPONENT_KEY='kanji5-v1.5-components',KNOWLEDGE_KEY='kanji5-v1.2-knowledge',LAST_ATTEMPT_KEY='kanji5-v1.2-last-attempt';
const $=(s,r=document)=>r.querySelector(s);
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);if(!raw)return fallback;const value=JSON.parse(raw);return value&&typeof value==='object'?value:fallback}catch(_){return fallback}}
function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(_) {}}
function normalize(value){return String(value??'').trim().toLowerCase().normalize('NFKC').replace(/[\s\u3000]+/g,'')}
function getDeck(){const data=window.__KANJI5_P0_DATA;if(Array.isArray(data)&&data.length)return data;const cached=readJSON('kanji5-deck',[]);return Array.isArray(cached)?cached:[]}
function ensureComponentEntry(character){const all=readJSON(COMPONENT_KEY,{});if(!all[character]||typeof all[character]!=='object')all[character]={meaning:{},reading:{},updatedAt:null};if(!all[character].meaning||typeof all[character].meaning!=='object')all[character].meaning={};if(!all[character].reading||typeof all[character].reading!=='object')all[character].reading={};return all}
function componentAccuracy(stats){const attempts=Math.max(0,Number(stats?.attempts)||0);if(!attempts)return 0;const correct=Math.min(attempts,Math.max(0,Number(stats?.correct)||0));const score=Number.isFinite(Number(stats?.score))?Math.max(0,Math.min(attempts,Number(stats.score))):correct;return(score+1)/(attempts+2)}
function componentSignal(entry){const out={};for(const mode of ['meaning','reading']){const values=Object.values(entry?.[mode]||{}).filter(v=>v&&typeof v==='object'&&(Number(v.attempts)||0)>0);if(!values.length){out[mode]={accuracy:null,weakness:null,attempts:0,lastAt:null};continue}let weight=0,total=0,lastAt=null;for(const v of values){const attempts=Math.max(0,Number(v.attempts)||0);weight+=attempts;total+=componentAccuracy(v)*attempts;const at=typeof v.lastAt==='string'?v.lastAt:'';if(at&&(lastAt===null||at>lastAt))lastAt=at}const accuracy=weight?total/weight:0;out[mode]={accuracy,weakness:Math.max(0,Math.min(1,1-accuracy)),attempts:weight,lastAt}}return out}
function writeSchedulerComponentEvidence(character){const all=readJSON(COMPONENT_KEY,{}),entry=all[character],knowledge=readJSON(KNOWLEDGE_KEY,{});if(!entry)return;const target=knowledge[character]&&typeof knowledge[character]==='object'?knowledge[character]:{};target.componentEvidence={...componentSignal(entry),updatedAt:entry.updatedAt||new Date().toISOString(),version:1};knowledge[character]=target;writeJSON(KNOWLEDGE_KEY,knowledge)}
function getFocusComponent(character,mode){const item=getDeck().find(x=>x&&x.character===character);if(!item)return null;const all=ensureComponentEntry(character),state=all[character][mode]||{},values=mode==='reading'?[...(item.on||[]),...(item.kun||[])]:[...(item.meaning||[])];const candidates=values.map(raw=>({raw,key:normalize(raw),accuracy:componentAccuracy(state[normalize(raw)]||{})}));candidates.sort((a,b)=>a.accuracy-b.accuracy);return candidates[0]||null}
function recordFocusedRecall(character,mode,focus,outcome){if(!character||!focus)return;const all=ensureComponentEntry(character),bucket=all[character][mode],key=normalize(focus),stats=bucket[key]||{attempts:0,correct:0,unknown:0,score:0,lastAt:null};stats.attempts+=1;if(outcome==='correct'){stats.correct+=1;stats.score+=1}else if(outcome==='unknown'){stats.unknown=(Number(stats.unknown)||0)+1;stats.score+=.25}stats.lastAt=new Date().toISOString();bucket[key]=stats;all[character].updatedAt=stats.lastAt;writeJSON(COMPONENT_KEY,all);writeSchedulerComponentEvidence(character)}
function inferMode(gate){return String(gate?.textContent||'').includes('خوانش')?'reading':'meaning'}
function mountRecallControl(gate){if(!gate||$('#v15DontKnowRecall',gate))return;if(!gate.dataset.v15Mode)gate.dataset.v15Mode=inferMode(gate);const character=String($('.kanji')?.textContent||'').trim();if(character&&!gate.dataset.v15Focus){const focus=getFocusComponent(character,gate.dataset.v15Mode);if(focus)gate.dataset.v15Focus=focus.raw}const nextPrompt=gate.dataset.v15Mode==='meaning'?'معنی این کانجی را از حافظه به یاد بیاور و پاسخ خودت را وارد کن.':'حداقل یک خوانش این کانجی را از حافظه به یاد بیاور و پاسخ خودت را وارد کن.';const prompt=[...gate.querySelectorAll('div')].find(node=>{const text=String(node.textContent||'').trim();return text.includes('معنی این کانجی')||text.includes('حداقل یک خوانش')});if(prompt&&prompt.textContent!==nextPrompt)prompt.textContent=nextPrompt;const input=gate.querySelector('input,textarea');if(!input)return;const button=document.createElement('button');button.type='button';button.id='v15DontKnowRecall';button.className='secondary';button.textContent='نمی‌دانم';button.style.width='100%';button.style.marginTop='9px';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const currentCharacter=String($('.kanji')?.textContent||'').trim();const mode=gate.dataset.v15Mode||inferMode(gate);const focus=gate.dataset.v15Focus||getFocusComponent(currentCharacter,mode)?.raw||'';if(currentCharacter)writeJSON(LAST_ATTEMPT_KEY,{character:currentCharacter,mode,attemptedAt:new Date().toISOString(),hadAttempt:true,correct:false,unknown:true});if(currentCharacter&&focus)recordFocusedRecall(currentCharacter,mode,focus,'unknown');const answer=$('#answerBox')||$('.answer'),ratings=$('#ratings');if(answer){answer.classList.add('show');answer.style.display='block'}if(ratings){ratings.classList.add('show');ratings.style.display='grid'}gate.remove()},false);input.parentElement?.appendChild(button)}
function installRecallGateBridge(){document.addEventListener('click',event=>{if(event.target?.id!=='revealBtn')return;setTimeout(()=>{const gate=$('.v12-recall-gate');if(gate)mountRecallControl(gate)},0)},true)}
function installBusyGuard(){document.addEventListener('click',event=>{const control=event.target?.closest?.('button,[role="button"]');if(!control||control.id==='v15DontKnowRecall')return;const root=control.closest?.('#educationPanel,.education-panel');if(!root||root.getAttribute('aria-busy')!=='true')return;event.preventDefault();event.stopImmediatePropagation()},true)}
function installTatoebaDeduper(){if(window.__KANJI5_V15_TATOEBA_DEDUP__)return;const nativeFetch=window.fetch?.bind(window);if(!nativeFetch)return;const inflight=new Map;window.fetch=(input,init)=>{const url=typeof input==='string'?input:input?.url||'',method=String(init?.method||input?.method||'GET').toUpperCase();if(method!=='GET'||!url.startsWith('https://api.tatoeba.org/v1/sentences'))return nativeFetch(input,init);const pending=inflight.get(url);if(pending)return pending.then(r=>r.clone());const request=nativeFetch(input,init).finally(()=>inflight.delete(url));inflight.set(url,request);return request.then(r=>r.clone())};window.__KANJI5_V15_TATOEBA_DEDUP__=true}
function installA11y(){if($('#v15-a11y-style'))return;const style=document.createElement('style');style.id='v15-a11y-style';style.textContent='button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,[role="button"]:focus-visible{outline:3px solid var(--accent,var(--primary,#4f46e5));outline-offset:3px}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}}';document.head.appendChild(style)}
installRecallGateBridge();installBusyGuard();installTatoebaDeduper();installA11y();
})();
