  await expect(pageRoot).toBeVisible();
  await expect(pageRoot.locator('.mastery-map-summary')).toHaveCount(0);
  await expect(pageRoot.locator('.kanji-catalog-tile').first()).toHaveAttribute('data-mastery-state');
  await expect(pageRoot.locator('.kanji-catalog-tile')).toHaveCount(2136,{timeout:10000});
  const n5=pageRoot.getByRole('button',{name:'N5',exact:true});
  await n5.click();
  await expect(n5).toHaveAttribute('aria-pressed','true');
  await expect.poll(async()=>pageRoot.locator('.kanji-catalog-tile').evaluateAll(nodes=>nodes.length>0&&nodes.every(node=>node.getAttribute('data-jlpt')==='N5'))).toBe(true);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.route("https://raw.githubusercontent.com/KanjiVG/kanjivg/422b5538595676da918c288a4230cb5e22a1ee7e/kanji/**.svg", async route => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg"><g id="kvg:StrokePaths_05b66"><path id="kvg:05b66-s1" d="M10,10 L30,30"/><path id="kvg:05b66-s2" d="M30,30 L50,10"/><path id="kvg:05b66-s3" d="M50,10 L70,30"/></g></svg>`;
    await route.fulfill({ status: 200, contentType: 'image/svg+xml', body: svg });
  });
  const sort=pageRoot.locator('.dictionary-sort select');
  await sort.selectOption('mastery-desc');
  await expect(sort).toHaveValue('mastery-desc');
  await pageRoot.getByRole('button',{name:'همه',exact:true}).click();
  const search=pageRoot.getByRole('textbox',{name:'کانجی، خوانش یا معنی را جست‌وجو کن'});
  await search.fill('学');
  const tile=pageRoot.locator('.kanji-catalog-tile').filter({hasText:'学'}).first();
  await expect(tile).toBeVisible({timeout:10000});
  await expect(tile).toHaveAttribute('data-jlpt','N5');
  await tile.click();
  const card=page.getByRole('dialog');
  await expect(card).toBeVisible();
  await search.fill('');
  await expect.poll(async()=>pageRoot.locator('.kanji-catalog-tile').count(),{timeout:10000}).toBeGreaterThan(1);
  await expect(card.locator('.dictionary-card-character')).toHaveCount(0);