import fs from 'node:fs';
import vm from 'node:vm';

const read=p=>fs.readFileSync(p,'utf8');
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const count=(text,needle)=>(text.split(needle).length-1);

const index=read('index.html'),runtime=read('v1.2-runtime-fixes.js'),sw=read('sw.js'),migration=read('v1.4-education-migration.js'),workflow=read('.github/workflows/build-v1.5.yml'),core=read('v1.4-education-core.js'),ui=read('v1.4-education-ui.js'),p0=read('v1.5-p0.js'),fsrsSync=read('v1.5-fsrs-sync-core.js'),supabase=read('supabase-sync.js');
const required=['./v1.3-p0.js','./v1.3-perf.js','./v1.3-storage-bridge.js','./v1.3-settings.js','./v1.4-education-migration.js','./v1.4-education-core.js','./v1.4-education-ui.js'];
for(const src of required)assert(count(index,`<script src="${src}"></script>` )===1,`${src} must be wired exactly once`);
assert(count(index,'<script src="./v1.5-p0.js"></script>')===1,'v1.5 P0 runtime must be loaded explicitly exactly once by the active HTML runtime');
assert(!runtime.includes('v1.5-p0.js'),'v1.2 runtime bridge must not duplicate-load v1.5 P0');
assert(!index.includes('v1.5-education-choice-enforcer.js')&&!runtime.includes('v1.5-education-choice-enforcer.js'),'Obsolete Production choice enforcer remains in the active runtime');
for(const legacy of ['./v1.3-p1.js','./v1.3-education-runtime-fix.js','./v1.3-production-ui.js','./v1.3-education-v2.js','./v1.3-dont-know.js','./v1.3-smart-distractors.js'])assert(!index.includes(legacy),`Legacy runtime remains: ${legacy}`);
assert(!index.includes('id="v1.2-mobile-fix"'),'Mobile CSS was not consolidated');
assert(!index.includes('id="v1.3-education"')&&!index.includes('id="v1.3-p1"'),'Legacy education CSS remains');
assert(count(index,'v1.2-dataset-2136')===1,'Duplicate dataset bootstrap remains');

class Store{constructor(values={}){this.values={...values}}getItem(k){return Object.prototype.hasOwnProperty.call(this.values,k)?this.values[k]:null}setItem(k,v){this.values[k]=String(v)}}
function runMigration(initial){const store=new Store(initial),ctx={window:{},localStorage:store,Date,JSON};vm.createContext(ctx);vm.runInContext(migration,ctx);assert(ctx.window.__KANJI5_EDU_MIGRATION_API__,'Migration API missing');return{store,api:ctx.window.__KANJI5_EDU_MIGRATION_API__}}
const fresh=runMigration({});
assert(fresh.api.version===2,'Fresh install migration version mismatch');assert(fresh.api.migrations.join(',')==='1,2','Migration chain is not versioned');
assert(JSON.parse(fresh.store.getItem('kanji5-v1.2-knowledge')||'{}')?.constructor===Object,'Fresh install store should remain valid JSON object');assert(fresh.store.getItem('kanji5-v1.4-education-meta'),'Fresh install metadata missing');
const legacyKnowledge={'学':{meaning:{attempts:4,correct:3,lastAt:'2026-08-20T00:00:00.000Z'},reading:{attempts:2,correct:1,lastAt:'2026-08-21T00:00:00.000Z'},distractors:{'校':2}},'校':{meaning:{attempts:0,correct:0}}};
const upgraded=runMigration({'kanji5-v1.2-knowledge':JSON.stringify(legacyKnowledge)}),migrated=JSON.parse(upgraded.store.getItem('kanji5-v1.2-knowledge'));
assert(migrated['学'].schemaVersion===2,'Upgrade did not reach current education schema');assert(migrated['学'].meaning.byDevice.legacy.attempts===4,'Migration chain did not preserve legacy attempts in device bucket');assert(migrated['学'].exposedAt,'Upgrade did not infer exposedAt from prior attempts');assert(migrated['学'].meaning.correct===3&&migrated['学'].meaning.attempts===4,'Upgrade changed historical meaning stats');assert(migrated['学'].reading.correct===1&&migrated['学'].reading.attempts===2,'Upgrade changed historical reading stats');assert(migrated['学'].distractors['校']===2,'Upgrade dropped distractor history');
const v1Meta={version:1};const upgradedV1=runMigration({'kanji5-v1.4-education-meta':JSON.stringify(v1Meta),'kanji5-v1.2-knowledge':JSON.stringify({'学':{schemaVersion:1,meaning:{attempts:2,correct:1,lastAt:'2026-08-25T00:00:00.000Z'}}})});assert(JSON.parse(upgradedV1.store.getItem('kanji5-v1.4-education-meta')).version===2,'Version-1 data was not advanced to version 2');assert(JSON.parse(upgradedV1.store.getItem('kanji5-v1.2-knowledge'))['学'].meaning.byDevice.legacy.attempts===2,'Version-1 migration did not execute v2 step');

assert(sw.includes("const API_ORIGIN='https://kanjiapi.dev'"),'kanjiapi origin missing from service worker');assert(sw.includes("const TATOEBA_ORIGIN='https://api.tatoeba.org'"),'Tatoeba origin missing from service worker');assert(sw.includes("u.origin===API_ORIGIN&&u.pathname.startsWith('/v1/words/')"),'Vocabulary API cache route missing');assert(sw.includes("u.origin===TATOEBA_ORIGIN&&u.pathname.startsWith('/v1/sentences')"),'Context API cache route missing');assert(sw.includes('kanji5-shell-v46')&&sw.includes('kanji5-api-v14'),'Cache versions are inconsistent with the current PWA shell');assert(sw.includes('async function staleWhileRevalidate'),'Navigation stale-while-revalidate helper missing');assert(sw.includes("if(r.mode==='navigate'){e.respondWith(staleWhileRevalidate"),'Navigation is not using stale-while-revalidate');assert(sw.includes('"./v1.5-state.js"'),'v1.5 state dependency is missing from the offline shell');assert(sw.includes('"./v1.5-education-sync-core.js"'),'Education sync dependency is missing from the offline shell');assert(sw.includes('"./v1.5-fsrs-sync-core.js"'),'FSRS sync dependency is missing from the offline shell');const dynamicStart=sw.indexOf('async function dynamicSameOrigin'),dynamicEnd=sw.indexOf("self.addEventListener('fetch'",dynamicStart),dynamicHelper=sw.slice(dynamicStart,dynamicEnd);assert(dynamicHelper.includes('fetch(req)')&&!dynamicHelper.includes('caches.'),'Dynamic same-origin caching must remain bounded');assert(!sw.includes("fetch(r).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(r,res.clone()));return res})"),'Unsafe post-return response.clone caching pattern remains');

assert(p0.includes('window.__KANJI5_V15_P0__'),'Canonical v1.5 P0 runtime version marker missing');assert(p0.includes('function enhanceRecall()'),'Active Recall enhancer missing');assert(p0.includes('function addDontKnowRecall()'),'Active Recall don’t-know enhancer missing');assert(p0.includes('v15DontKnowRecall'),'Active Recall don’t-know control missing');assert(p0.includes("recordFocusedRecall(character,mode,focus,'unknown')"),'Unknown recall is not recorded as a separate outcome');assert(p0.includes('stats.score+=.25'),'Unknown recall must have a lighter educational weight than correct recall');assert(!p0.includes('v15DontKnowReview'),'Don’t-know must not be a review-rating control');assert(!p0.includes('.rate.again'),'Don’t-know must not directly trigger FSRS Again');assert(!p0.includes('function enhanceProduction'),'Production renderer must remain in the canonical education UI');assert(!p0.includes('getProductionTarget'),'Production target inference must not live in P0');assert(!p0.includes('data-v15Production'),'Production choice handling must remain in the canonical education UI');assert(!p0.includes('observer.observe(document.body'),'P0 must not install a global document.body observer');assert(!p0.includes('||document.body'),'P0 observer must not fall back to the document body');assert(p0.includes('function startTargetedObservers()')&&p0.includes('studyRoot'),'P0 must use a targeted study observer');assert(p0.includes('gate.dataset.v15Focus=focus.raw')&&!p0.includes('معنی هدف:')&&!p0.includes('خوانش هدف:'),'Active Recall must keep the focus internally without leaking it in the prompt');assert(runtime.includes('loading.classList.add("v13-real-error")'),'Startup errors must opt into the visible error-panel CSS override');
assert(!fs.existsSync('package.json'),'Unexpected package.json dependency surface introduced');for(const forbidden of ['npm install ','https://unpkg.com/','https://cdn.jsdelivr.net/'])assert(!index.includes(forbidden)&&!ui.includes(forbidden),`Unexpected runtime dependency: ${forbidden}`);assert(index.includes('./vendor/ts-fsrs-5.4.1.mjs'),'Pinned local FSRS vendor missing');assert(core.includes('educationSchedulerSignal')&&core.includes('chooseDistractors'),'Updated education core is not present');assert(ui.includes('CORE.chooseDistractors'),'UI is not using canonical distractor selection');assert(ui.includes('CORE.selectEducationItem'),'UI is not using adaptive Kanji selection');assert(ui.includes('safe(edu.sentence.english||\'\')'),'Context translation escaping is not wired');assert(workflow.includes('scripts/test-v1.5-p0.mjs')&&workflow.includes('scripts/test-v1.4-p1.mjs')&&workflow.includes('scripts/test-v1.4-education.mjs')&&workflow.includes('scripts/test-v1.5-fsrs-sync.mjs'),'Education and FSRS CI gates are missing');assert(!workflow.includes('git push origin feature/v1.5'),'v1.5 CI must not self-push generated changes');assert(workflow.includes('test "$(git status --porcelain)" = ""'),'v1.5 CI must fail on committed-build drift');assert(index.includes('function educationQueuePriority'),'Education/FSRS queue bridge is missing');assert(index.includes('educationQueuePriority(k')||index.includes('educationQueuePriority(item'),'Queue does not use education priority');assert(index.includes('dueItems')&&index.includes('dueItems.sort'),'FSRS due cards are not being ranked with education evidence');assert(!index.includes('scheduler.next(rec.card,now,education'),'FSRS rating path was not replaced by education heuristic');
assert(supabase.includes('const EDUCATION_SCHEMA_VERSION = 2'),'Supabase education schema version is stale');assert(supabase.includes('function withSyncLock'),'Supabase sync must be single-flight');assert(supabase.includes('sameDayLocal')&&supabase.includes('sameDayRemote'),'Daily sync counters must be date-aware');assert(fsrsSync.includes('isPreEventSnapshot')&&fsrsSync.includes('legacyRoots'),'FSRS replay must distinguish safe pre-event snapshots from legacy post-event roots');
console.log('Kanji 5 v1.5 P0 stabilization smoke suite passed.');
