import fs from 'node:fs';
import vm from 'node:vm';

const coreSource=fs.readFileSync('v1.4-education-core.js','utf8');
const migration=fs.readFileSync('v1.4-education-migration.js','utf8');
const ui=fs.readFileSync('v1.4-education-ui.js','utf8');
const sync=fs.readFileSync('supabase-sync.js','utf8');
const ctx={window:{},structuredClone:global.structuredClone,localStorage:{getItem(){return null},setItem(){}}};
vm.createContext(ctx);vm.runInContext(coreSource,ctx);
const core=ctx.window.__KANJI5_EDU_CORE__;const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(core,'core missing');
assert(['meaning','reading','production','vocabulary','context'].every(m=>core.registry[m]),'registry incomplete');
assert(core.chooseBestExercise({character:'学'},{meaning:{attempts:9,correct:9},reading:{attempts:8,correct:2},production:{attempts:8,correct:1},vocabulary:{attempts:8,correct:1},context:{attempts:8,correct:1}},core.modes,{now:Date.now()})==='production','weakest skill was not prioritized');
const qualified=core.gradeMeaning('school work',['school work','education']);assert(qualified.correct&&qualified.quality==='exact','meaning exact grading failed');
const partial=core.gradeMeaning('school',['school system']);assert(partial.correct&&partial.quality==='partial','meaning partial grading failed');
assert(!core.gradeMeaning('schol',['school']).correct,'invalid typo was accepted');
assert(core.gradeReading('gaku',['がく']).correct,'reading grading failed');
assert(core.gradeReading('mo',['も']).correct,'Romaji も grading regressed');
let k=core.ensureEntry({},'学',true)['学'];assert(k.exposedAt&&k.stage==='exposed','exposure state initialization failed');
k=core.recordKnowledge({'学':k},'学','production',false,'校')['学'];assert(k.production.attempts===1&&k.distractors['校']===1,'knowledge recording failed');
assert(migration.includes('schemaVersion=1')&&migration.includes('kanji5-v1.4-education-meta'),'migration missing');
assert(ui.includes('CORE.chooseBestExercise')&&ui.includes('CORE.gradeMeaning')&&ui.includes('CORE.gradeReading')&&ui.includes('CORE.recordKnowledge'),'UI bypasses core');
assert(ui.includes('v14EduProductionInput'),'typed production UI missing');
assert(ui.includes('context')&&ui.includes('vocabulary'),'vocabulary/context missing');
assert(ui.includes('تمرین بعدی'),'next exercise flow missing');
assert(sync.includes('production')&&sync.includes('vocabulary')&&sync.includes('context'),'sync merge does not cover all educational modes');
assert(sync.includes('distractors')&&sync.includes('stage'),'sync educational metadata missing');
console.log('Kanji 5 v1.4 P1 tests passed.');
