import fs from 'node:fs';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const patchIndex=()=>{const path='index.html';let s=fs.readFileSync(path,'utf8');const marker='const todayKey=()=>new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());';const helper=marker+'\nconst DEVICE_KEY="kanji5-device-id";\nfunction deviceId(){try{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=(crypto.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem(DEVICE_KEY,id)}return id}catch(_){return "legacy"}}\nfunction eventId(){return crypto.randomUUID?.()||`review-${Date.now()}-${Math.random().toString(36).slice(2)}`}';assert(s.includes(marker),'P1-2 index marker missing');if(!s.includes('const DEVICE_KEY="kanji5-device-id"'))s=s.replace(marker,helper);const old='state.reviews.push({id,at:now.toISOString(),rating:which,due:rec.card.due,scheduledDays:rec.card.scheduled_days||0});';const next='const previousEvent=[...state.reviews].reverse().find(r=>r.id===id&&r.eventId)?.eventId||null;const reviewEventId=eventId();const reviewDeviceId=deviceId();const baseRecord=structuredClone({...rec,card:reviveCard(structuredClone(rec.card))});state.reviews.push({eventId:reviewEventId,deviceId:reviewDeviceId,parentEventId:previousEvent,baseRecord,id,at:now.toISOString(),rating:which,due:rec.card.due,scheduledDays:rec.card.scheduled_days||0});';assert(s.includes(old),'P1-2 review event insertion point missing');if(!s.includes('parentEventId:previousEvent'))s=s.replace(old,next);fs.writeFileSync(path,s)};
const patchSync=()=>{const path='supabase-sync.js';let s=fs.readFileSync(path,'utf8');const oldImport="import { mergeModeStats as mergeEducationModeStats, mergeKnowledgeEntry as mergeEducationKnowledgeEntry, mergeKnowledge as mergeEducationKnowledge } from './v1.5-education-sync-core.js';";const newImport=oldImport+"\nimport { mergeReviewEvents, replayCards } from './v1.5-fsrs-sync-core.js';\nimport { fsrs } from './vendor/ts-fsrs-5.4.1.mjs';";assert(s.includes(oldImport),'P1-2 sync import marker missing');if(!s.includes("./v1.5-fsrs-sync-core.js"))s=s.replace(oldImport,newImport);const start=s.indexOf('    const ids = new Set([...Object.keys(local.cards || {}), ...Object.keys(remote.cards || {})]);');const endMarker='    merged.reviews = [...reviewMap.values()].sort((a, b) => String(a.at).localeCompare(String(b.at))).slice(-5000);';const end=s.indexOf(endMarker,start);assert(start>=0&&end>=0,'P1-2 card/review merge block missing');const newCards=`    const ids = new Set([...Object.keys(local.cards || {}), ...Object.keys(remote.cards || {})]);
    merged.cards = {};
    for (const id of ids) {
      const lc = local.cards?.[id], rc = remote.cards?.[id];
      if (!lc) merged.cards[id] = rc;
      else if (!rc) merged.cards[id] = lc;
      else merged.cards[id] = lastReviewAt(local, id) >= lastReviewAt(remote, id) ? lc : rc;
    }
    merged.reviews = mergeReviewEvents(reviewsFor(local), reviewsFor(remote), 5000);
    const replayable = merged.reviews.filter(event => event.eventId && event.baseRecord);
    if (replayable.length) {
      const settings = { retention: Number(merged.settings?.retention) || 0.90, maxInterval: Number(merged.settings?.maxInterval) || 36500 };
      merged.cards = replayCards(merged.cards, replayable, () => { const scheduler=fsrs({request_retention:settings.retention,maximum_interval:settings.maxInterval,enable_fuzz:true,enable_short_term:true,learning_steps:["1m","10m"],relearning_steps:["10m"]}); return {next:scheduler.next.bind(scheduler),Rating:{Again:1,Hard:2,Good:3,Easy:4}}; }, Number(merged.settings?.leechThreshold) || 8);
    }`;
s=s.slice(0,start)+newCards+s.slice(end+endMarker.length);fs.writeFileSync(path,s)};
patchIndex();patchSync();assert(fs.readFileSync('index.html','utf8').includes('parentEventId:previousEvent'),'P1-2 review events not persisted');assert(fs.readFileSync('supabase-sync.js','utf8').includes('mergeReviewEvents'),'P1-2 event merge not wired');console.log('P1-2 patch stage applied.');
