import fs from 'node:fs';
const path='sw.js';let s=fs.readFileSync(path,'utf8');const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(s.includes("const API_CACHE='kanji5-api-v14';"),'API cache marker missing');
if(!s.includes('const API_TTL_MS='))s=s.replace("const TATOEBA_ORIGIN='https://api.tatoeba.org';","const TATOEBA_ORIGIN='https://api.tatoeba.org';\nconst API_TTL_MS=7*24*60*60*1000;\nconst API_MAX_ENTRIES=250;");
const re=/async function apiCacheFirst\(req\)\{[\s\S]*?\n\}\nasync function dynamicSameOrigin/;
const replacement=`async function cacheApiResponse(cache,req,response){if(!response||response.type==='opaque'||!response.ok)return;try{const body=await response.clone().blob();const headers=new Headers(response.headers);headers.set('X-Kanji5-Cache-Time',String(Date.now()));await cache.put(req,new Response(body,{status:response.status,statusText:response.statusText,headers}))}catch(_){} }
async function evictApiCache(cache){const keys=await cache.keys(),now=Date.now();for(const key of keys){const hit=await cache.match(key);const stamp=Number(hit?.headers.get('X-Kanji5-Cache-Time')||0);if(stamp&&now-stamp>API_TTL_MS)await cache.delete(key)}const fresh=await cache.keys();if(fresh.length<=API_MAX_ENTRIES)return;const ranked=[];for(const key of fresh){const hit=await cache.match(key);ranked.push({key,stamp:Number(hit?.headers.get('X-Kanji5-Cache-Time')||0)})}ranked.sort((a,b)=>a.stamp-b.stamp);for(const item of ranked.slice(0,Math.max(0,ranked.length-API_MAX_ENTRIES)))await cache.delete(item.key)}
async function apiCacheFirst(req){const c=await caches.open(API_CACHE);const hit=await c.match(req);if(hit){const stamp=Number(hit.headers.get('X-Kanji5-Cache-Time')||0);if(stamp&&Date.now()-stamp<=API_TTL_MS){void evictApiCache(c);return hit}if(stamp)await c.delete(req)}try{const r=await fetch(req);await cacheApiResponse(c,req,r);void evictApiCache(c);return r}catch(_){const fallback=await c.match(req);return fallback||Response.error()}}
async function dynamicSameOrigin`;
assert(re.test(s),'API cache helper not found');s=s.replace(re,replacement);fs.writeFileSync(path,s);
const out=fs.readFileSync(path,'utf8');assert(out.includes('API_TTL_MS=7*24*60*60*1000'),'API cache TTL missing');assert(out.includes('API_MAX_ENTRIES=250'),'API cache entry bound missing');assert(out.includes('X-Kanji5-Cache-Time'),'API cache timestamp metadata missing');assert(out.includes('Date.now()-stamp<=API_TTL_MS'),'API cache hit TTL is not enforced');assert(out.includes('ranked.slice(0,Math.max(0,ranked.length-API_MAX_ENTRIES))'),'API cache eviction bound missing');console.log('P2-2 API cache TTL/eviction patch passed.');
